### ISSUE TITLE
a problem after latest update 

### ISSUE THREAD

**Issue by dinamoedm** [EricJMarti/inventory-hunter#183]
Hi Folks ,

I've noticed this in the container log after latest update : 

starting: python /src/worker/lean_and_mean.py

Traceback (most recent call last):

File "/src/worker/lean_and_mean.py", line 81, in <module>

asyncio.run(main())

File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run

return loop.run_until_complete(main)

File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete

return future.result()

File "/src/worker/lean_and_mean.py", line 75, in main

server = await asyncio.start_server(handle, args.host, args.port)

File "/usr/local/lib/python3.9/asyncio/streams.py", line 94, in start_server

return await loop.create_server(factory, host, port, **kwds)

File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1494, in create_server

raise OSError(err.errno, 'error while attempting '

OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 3080): address already in use

I2021-03-24 00:02:53,156 [nwgg_c_2] not in stock

I2021-03-24 00:02:58,837 [nwgg_c_3] not in stock

**Comment by dinamoedm** [comment]
Sorry guys , False alarm ... reinstalled the code and everything looks good
