### ISSUE TITLE
Ver 1.6.7 Second or Third container problem.

### ISSUE THREAD

**Issue by dinamoedm** [EricJMarti/inventory-hunter#189]
After an upgrade to 1.6.7  I've noticed that the first docker container starts with no problem : 

starting: python /src/run_worker.py lean_and_mean
I2021-03-29 21:44:00,246 [root] starting v1.6.7 with args: /src/run.py --alerter discord --webhook https://discord.com/api/webhooks/797697372788097035/pP1L6iv1dtHK4cdURg5h7y1rAlAYrstYJzgK-
I2021-03-29 21:44:00,460 [root] discord alerter initialized with kwargs:

But any container after that looks like this : 

starting: python /src/run_worker.py lean_and_mean
I2021-03-29 21:44:54,377 [root] starting v1.6.7 with args: /src/run.py --alerter discord --webhook https://discord.com/api/webhooks/797697372788097035/pP1L6iv1dtHK4cdURg5h7y1rAlAYrstYJzg
Traceback (most recent call last):
File "/src/run_worker.py", line 28, in <module>
main()
File "/src/run_worker.py", line 24, in main
pkg.run()
File "/src/worker/lean_and_mean.py", line 48, in run
server.run()
File "/src/worker/server.py", line 46, in run
asyncio.run(self.run_impl())
File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
return future.result()
File "/src/worker/server.py", line 41, in run_impl
server = await asyncio.start_server(self.handle, self._endpoint.addr, self._endpoint.port)
File "/usr/local/lib/python3.9/asyncio/streams.py", line 94, in start_server
return await loop.create_server(factory, host, port, **kwds)
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 3080): address already in use
I2021-03-29 21:44:54,588 [root] discord alerter initialized with kwargs:

**Comment by yardbro** [comment]
can confirm this is now an issue with running more than one container

**Comment by dinamoedm** [comment]
The scraper itself is working fine though , I think .

**Comment by yardbro** [comment]
> The scraper itself is working fine though , I think .

indeed it would appear that the scraper itself is still working properly regardless of the error in the logs. It still reports 100% success rate for all of the items i have it looking for.
