### ISSUE TITLE
[Question] is it possible to run this on an Ubuntu cloud server?

### ISSUE THREAD

**Issue by panda-hackerman** [EricJMarti/inventory-hunter#19]
I've been trying to run this on Ubuntu, and everything seems to be working fine up until it detects an item in stock, and then I get errors. I've tested the SMTP relay and Docker and they both seem to be working fine. I don't have a raspberry pi but I already had the Ubuntu server for another project and figured it could do.
After I run the program with `./docker_run.bash -c /root/inventory-hunter/config/newegg_rtx_3070.yaml -e myemail@gmail.com -r [smtp.gmail.com]:587`, the logs look normal until it gets to the 2070 Super, then it logs it as in stock and then I get the following errors:
```
Traceback (most recent call last):
  File "/src/run.py", line 32, in main
    hunt(args, config, driver)
  File "/src/hunter.py", line 121, in hunt
    engine.run()
  File "/src/hunter.py", line 43, in run
    self.scheduler.run(blocking=True)
  File "/usr/local/lib/python3.9/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/src/hunter.py", line 58, in tick
    self.process_scrape_result(s, result)
  File "/src/hunter.py", line 95, in process_scrape_result
    self.send_alert(s, result, f'now in stock at {current_price}!')
  File "/src/hunter.py", line 116, in send_alert
    self.alerter(result.alert_subject, result.alert_content)
  File "/src/hunter.py", line 27, in __call__
    with smtplib.SMTP(self.relay) as s:
  File "/usr/local/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.9/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
```
I tried looking at the source code and I couldn't figure out if it was a compatibility problem or it I was missing something, but my python knowledge is very limited. Any help would be appreciated.

**Comment by Wood578Guy** [comment]
Replace `-r [smtp.gmail.com]:587` with `-r 127.0.0.1` - that server and port should be configured already in the SMTP relay you configured.

**Comment by panda-hackerman** [comment]
I used `-r 127.0.01` instead and I get an almost identical error. I'm running on a more recent version of Ubuntu (20.10), I'm not sure if that could be causing problems.

**Comment by EricJMarti** [comment]
In case you are still having issues setting up an SMTP relay, please consider using Discord or Slack: https://github.com/EricJMarti/inventory-hunter/issues/37#issuecomment-736900742
