### ISSUE TITLE
email alerter failed to alert

### ISSUE THREAD

**Issue by lavaplanet12** [EricJMarti/inventory-hunter#207]
E2021-05-01 20:14:48,832 [root] email alerter failed to alert
Traceback (most recent call last):
  File "/src/alerter/common.py", line 38, in __call__
    alerter(**kwargs)
  File "/src/alerter/emailer.py", line 50, in __call__
    msg["Subject"] = set_subject
  File "/usr/local/lib/python3.9/email/message.py", line 409, in __setitem__
    self._headers.append(self.policy.header_store_parse(name, val))
  File "/usr/local/lib/python3.9/email/policy.py", line 146, in header_store_parse
    raise ValueError("Header values may not contain linefeed "
ValueError: Header values may not contain linefeed or carriage return characters

**Comment by Remanent** [comment]
Duplicate of https://github.com/EricJMarti/inventory-hunter/issues/204#issue-859442255

**Comment by ridsama** [comment]
Have the same issue, sendmail works. Relay set to 127.0.0.1.
