### ISSUE TITLE
Getting an issue for the email sending to myself any help is appreciated

### ISSUE THREAD

**Issue by TheBingPlays** [EricJMarti/inventory-hunter#30]
I2020-11-30 23:48:45,139 gigabyte-geforce-rtx-2070-super-gv-n207swf3oc-8gd: now in stock at 859.9!
E2020-11-30 23:48:45,610 caught exception
Traceback (most recent call last):
  File "/src/run.py", line 32, in main
    hunt(args, config, driver)
  File "/src/hunter.py", line 121, in hunt
    engine.run()
  File "/src/hunter.py", line 43, in run
    self.scheduler.run(blocking=True)
  File "/usr/local/lib/python3.9/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/src/hunter.py", line 58, in tick
    self.process_scrape_result(s, result)
  File "/src/hunter.py", line 95, in process_scrape_result
    self.send_alert(s, result, f'now in stock at {current_price}!')
  File "/src/hunter.py", line 116, in send_alert
    self.alerter(result.alert_subject, result.alert_content)
  File "/src/hunter.py", line 29, in __call__
    s.send_message(msg)
  File "/usr/local/lib/python3.9/smtplib.py", line 970, in send_message
    return self.sendmail(from_addr, to_addrs, flatmsg, mail_options,
  File "/usr/local/lib/python3.9/smtplib.py", line 885, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'myemail@gmail.com': (454, b'4.7.1 <myemail@gmail.com>: Relay access denied')}

**Comment by ramansrivastava** [comment]
hey can i get assigned

**Comment by TheBingPlays** [comment]
figured out the solution. cant use my local ip address (192.168.1.6) as relay address.

had to use localhost (127.0.0.1)
