### ISSUE TITLE
No docker container after docker_run.bash

### ISSUE THREAD

**Issue by teototaro** [EricJMarti/inventory-hunter#88]
I'm facing the following problem: on a fresh Raspian headless installation (on Raspberry Pi 3 B+) I installed Docker and pulled the repo. After the execution of the command
`./docker_run.bash -c ./config/rtx3080.yaml -a slack -w https://hooks.slack.com/services/......`

I can see this output:

```
latest: Pulling from ericjmarti/inventory-hunter
Digest: sha256:51be37ee94ad6ce56f7b375da129e6db929a392b3ab5b0015237c9c539d6befb
Status: Image is up to date for ericjmarti/inventory-hunter:latest
docker.io/ericjmarti/inventory-hunter:latest
94a9706293bf079f7d8bf5a944b9cda019bb156666bcfaaeb7c8a09a7a2c9d1f

started docker container named rtx3080

view the status of this container using the following command:
$ docker ps -a -f name=rtx3080

CONTAINER ID   IMAGE                                COMMAND                  CREATED        STATUS                  PORTS     NAMES
94a9706293bf   ericjmarti/inventory-hunter:latest   "bash /src/run.bash …"   1 second ago   Up Less than a second             rtx3080

view logs for this container using the following command:
$ docker logs -f rtx3080
```

1. executing `docker ps -a -f name=rtx3080` I cannot see the container
2. executing `docker logs -f rtx3080` the system retrieves me `Error: No such container: rtx3080`

This is the content of my /config/rtx3080.yaml (I commented all the urls except the first to test):

```
---
urls:
  - https://www.amazon.it/EVGA-11G-P4-2487-KR-scheda-video-GeForce/dp/B07K6H583G
  #- https://www.amazon.it/Gigabyte-GeForce-GAMING-GV-N3080GAMING-OC-10GD/dp/B08HLZXHZY
  #- https://www.amazon.it/Gigabyte-AORUS-GeForce-3080-MASTER/dp/B08KHLDS72
  #- https://www.amazon.it/dp/B08HLZXHZY
  #- https://www.amazon.it/Gigabyte-GeForce-RTX-3080-EAGLE/dp/B08HHZVZ3N
  #- https://www.amazon.it/Scheda-grafica-Geforce-RTX-3080/dp/B08HR1NPPQ
  #- https://www.amazon.it/GeForce-GDDR6X-dissipatore-triventola-refresh/dp/B08HN37VQK
  #- https://www.amazon.it/EVGA-GeForce-10G-P5-3895-KR-Technology-Backplate/dp/B08HGBYWQ6
...
```

What am I doing wrong?

**Comment by EricJMarti** [comment]
It looks like the container is crashing and disappearing immediately because of the "--rm" flag on line 83 of `docker_run.bash`. Can you edit out that argument in `docker_run.bash` and try again so we can see why it's crashing?

**Comment by teototaro** [comment]
Now the output of `docker logs -f rtx3080` is:

```
D2020-12-10 12:42:08,752 [root] starting v1.2.0 with args: /src/run.py --alerter slack --webhook https://hooks.slack.com/services/[..].
D2020-12-10 12:42:09,463 [root] registering alerter type: discord
D2020-12-10 12:42:09,506 [root] registering alerter type: email
D2020-12-10 12:42:09,510 [root] registering alerter type: slack
D2020-12-10 12:42:09,515 [root] registering alerter type: telegram
D2020-12-10 12:42:10,244 [root] registering custom scraper for domain: amazon
D2020-12-10 12:42:10,248 [root] registering custom scraper for domain: bestbuy
D2020-12-10 12:42:10,253 [root] registering custom scraper for domain: bhphotovideo
D2020-12-10 12:42:10,257 [root] registering custom scraper for domain: microcenter
D2020-12-10 12:42:10,263 [root] registering custom scraper for domain: newegg
D2020-12-10 12:42:10,267 [root] registering custom scraper for domain: walmart
E2020-12-10 12:42:10,286 [root] caught exception
Traceback (most recent call last):
  File "/src/run.py", line 49, in main
    alerters = init_alerters(args)
  File "/src/alerter/__init__.py", line 10, in init_alerters
    return AlerterFactory.create(args)
  File "/src/alerter/common.py", line 49, in create
    return cls.create_from_args(args)
  File "/src/alerter/common.py", line 56, in create_from_args
    return AlertEngine([alerter.from_args(args)])
  File "/src/alerter/slack.py", line 17, in from_args
    return cls(webhook_url=webhook_url)
TypeError: __init__() got an unexpected keyword argument 'webhook_url'
```

**Comment by EricJMarti** [comment]
This is fixed in: https://github.com/EricJMarti/inventory-hunter/commit/086c04b0ecccd22570318dee8fcd5dd7fb8cda56

The fix is building and should be available on Docker Hub in about 20 minutes.
