### ISSUE TITLE
3090 configuration?

### ISSUE THREAD

**Issue by garrett1415** [EricJMarti/inventory-hunter#92]
I was able to get the 3080 and ps5 configs to work. However, I am looking for a 3090 - I edited a config file with 3090 links and named it bestbuy_rtx_3090. When I run it and check the logs it returns 'no such container'. Not sure where I am going wrong.

**Comment by EricJMarti** [comment]
It looks like the container is crashing and disappearing immediately because of the "--rm" flag on line 83 of `docker_run.bash`. Can you edit out that argument in `docker_run.bash` and try again so we can see why it's crashing?

**Comment by garrett1415** [comment]
Tried the suggested. Looks like it initiated and exited:

```
pi@raspberrypi:~/inventory-hunter $ docker ps -a -f name=rtx3090
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                      PORTS     NAMES
df5b5b6575cc   ericjmarti/inventory-hunter:latest   "bash /src/run.bash …"   22 seconds ago   Exited (1) 18 seconds ago             rtx3090
pi@raspberrypi:~/inventory-hunter $ docker logs -f rtx3090
D2020-12-12 18:00:07,691 [root] starting v1.2.3 with args: /src/run.py --alerter discord --webhook https://discord.com/api/webhooks/786622787271131137/bqSJH3FieYp7TnbloU0CiIksMUJ0Ur3AzivupV3wF6pYwOO7oCquyV71Ck6B5QiSbCq4
D2020-12-12 18:00:08,186 [root] registering alerter type: discord
D2020-12-12 18:00:08,215 [root] registering alerter type: email
D2020-12-12 18:00:08,218 [root] registering alerter type: slack
D2020-12-12 18:00:08,221 [root] registering alerter type: telegram
D2020-12-12 18:00:08,787 [root] registering custom scraper for domain: amazon
D2020-12-12 18:00:08,791 [root] registering custom scraper for domain: bestbuy
D2020-12-12 18:00:08,794 [root] registering custom scraper for domain: bhphotovideo
D2020-12-12 18:00:08,798 [root] registering custom scraper for domain: microcenter
D2020-12-12 18:00:08,803 [root] registering custom scraper for domain: newegg
D2020-12-12 18:00:08,806 [root] registering custom scraper for domain: walmart
I2020-12-12 18:00:08,819 [root] discord alerter initialized with kwargs: webhook_url=https://discord.com/api/webhooks/786622787271131137/bqSJH3FieYp7TnbloU0CiIksMUJ0Ur3AzivupV3wF6pYwOO7oCquyV71Ck6B5QiSbCq4
E2020-12-12 18:00:08,836 [root] caught exception
Traceback (most recent call last):
  File "/src/run.py", line 50, in main
    config = parse_config(args.config)
  File "/src/config.py", line 46, in parse_config
    data = yaml.safe_load(f)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/local/lib/python3.9/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.9/site-packages/yaml/parser.py", line 382, in parse_block_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/usr/local/lib/python3.9/site-packages/yaml/scanner.py", line 258, in fetch_more_tokens
    raise ScannerError("while scanning for the next token", None,
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/config.yaml", line 23, column 1

```

**Comment by EricJMarti** [comment]
It looks like you have tabs in your YAML file. Can you try switching these tabs to spaces?

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @garrett1415)
